[tox]
envlist = py39,py310,py311,py312,py313,lint,type
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    pytest-cov
    hypothesis
commands = pytest --cov=pyshamir --cov-report=term-missing

[testenv:lint]
deps = ruff
commands =
    ruff check pyshamir tests
    ruff format --check pyshamir tests

[testenv:type]
deps = mypy
commands = mypy pyshamir

[testenv:coverage]
deps =
    pytest
    pytest-cov
    hypothesis
commands = pytest --cov=pyshamir --cov-report=xml --cov-report=html --cov-report=term-missing
