name: Unit Test & Reporting

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unittesting:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Run Tests and Coverage
      continue-on-error: false
      run: |
        python -m coverage run --source pyshamir -m unittest discover -p test_*.py
        python -m coverage xml
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ github.token }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args:
          -Dsonar.projectKey=konidev20_pyshamir
          -Dsonar.organization=konidev20
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=pyshamir

