name: Unit Test & Reporting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Files
      uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Run Tests and Coverage
      continue-on-error: true
      run: |
        ls
        python -m unittest discover -s ./tests -p test_*.py
